download_tiles.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: inputs/tiles
  aoi: inputs/vectors/pilot_v3.gpkg
  buffer: 100
  method: stochastic_depressions
  overwrite: False


merge_dem_over_aoi.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/merged_DEM/stoch_deps
  dem_dir: inputs/tiles
  dem_correspondence: inputs/tiles/dem_per_aoi_stochastic_depressions.csv
  aoi: inputs/vectors/pilot_v3.gpkg
  res: 1.5


wbt_stochastic_depressions.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/stochastic_depressions
  dem_dir: outputs/merged_DEM/stoch_deps
  # rmse: 0.5             # The docs recommand a value between 0.15 and 0.3 for LiDAR data or the vertical accuracy
  autocorr_range: 5    # 3 to 15 times the resolution. Test for 3, 5 and 8 times the resolution.
  iterations: 100       # 100 to 500 is generally enough
  threshold: 0.9
  non_sedimentary_areas: inputs/vectors/non_sedimentary.parquet
  builtup_areas: inputs/vectors/restricted_siedlung_2024_2056.gpkg


post_processing.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/stochastic_depressions
  potential_dolines: outputs/stochastic_depressions/potential_dolines.gpkg
  tlm_data: inputs/vectors/side_data/clipped_tlm_subset.gpkg
  ground_cover_layer: tlm_bb_bodenbedeckung
  rivers: inputs/vectors/side_data/clipped_typisierung-fliessgewaesser_2056.gpkg
  parameters:
    max_part_in_lake: 0.1
    max_part_in_river: 0.15
    min_compactness: 0.45
    min_area: 20
    max_area: 2500
    min_diameter: 5
    min_depth: 1.8
    max_depth: 80
    max_std_elev: 5


assess_results.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/assessment
  dem_dir: outputs/merged_DEM/stoch_deps
  ref_data:
    tlm_data: inputs/vectors/TLM-Dolinen-20240814/tlm-dolinen_20240814.gpkg
    merged_reference: inputs/vectors/new_gt/ref_data.gpkg
    ground_truth: inputs/vectors/new_gt/ground_truth.gpkg
  detections:
    stochastic_depressions: outputs/stochastic_depressions/dolines.gpkg
  pilot_areas: inputs/vectors/pilot_v3.gpkg
  type:
    ref_data: ground_truth
    dets: stochastic_depressions


optimization_stochastic_deps.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/optimization/stochastic_depressions
  tile_dir: inputs/tiles
  ref_type: ground_truth
  ref_data:
    merged_reference: inputs/vectors/new_gt/ref_data.gpkg
    ground_truth: inputs/vectors/new_gt/ground_truth.gpkg
  study_param:
    new_study: True
    optimize: True
    iterations: 50
  aoi: inputs/vectors/pilot_v3.gpkg
  dem_correspondence: inputs/tiles/dem_per_aoi_stochastic_depressions.csv
  non_sedimentary_areas: outputs/merged_DEM/ign/possible_areas/non_sedi_areas.gpkg
  builtup_areas: inputs/vectors/restricted_siedlung_2024_2056.gpkg
  tlm_data: inputs/vectors/side_data/clipped_tlm_subset.gpkg
  ground_cover_layer: tlm_bb_bodenbedeckung
  rivers: inputs/vectors/side_data/clipped_typisierung-fliessgewaesser_2056.gpkg