download_tiles.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: inputs/tiles_ign
  aoi: inputs/vectors/pilot_v2.geojson
  buffer: 500
  overwrite: False


merge_dem_over_aoi.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/merged_DEM/ign
  dem_dir: inputs/tiles_ign
  dem_correspondence: inputs/tiles_ign/dem_per_aoi.csv
  aoi: inputs/vectors/pilot_v2.geojson
  # res: 3


gt_analysis.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/GT_analysis
  dem_dir: outputs/merged_DEM/ign
  slope_dir: outputs/merged_DEM/ign/slope
  aoi: inputs/vectors/pilot_v2.geojson
  dolines: inputs/vectors/dolines.gpkg
  ref_type: geocover


get_slope.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/merged_DEM/ign/slope
  dem_dir: outputs/merged_DEM/ign


define_possible_areas.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/merged_DEM/ign/possible_areas
  slope_dir: outputs/merged_DEM/ign/slope
  non_sedimentary_areas: inputs/vectors/non_sedimentary.parquet
  aoi: inputs/vectors/pilot_v2.geojson
  # max_slope: 1.5


treatment_mask.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/dolines/ign/treatment_mask
  dem_dir: outputs/merged_DEM/ign


doline_detection.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/dolines/ign
  dem_dir: outputs/merged_DEM/ign


doline_detection_original.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/dolines/ign/full_IGN_params
  dem_dir: outputs/merged_DEM/ign_5m
  mask_dir: outputs/treatment_mask


assess_results.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/assessment
  dem_dir: outputs/merged_DEM/ign
  ref_data:
    merged_reference: inputs/vectors/new_gt/ref_data.gpkg
    ground_truth: inputs/vectors/new_gt/ground_truth.gpkg
  detections:
    ign: outputs/ign/sinkholes.gpkg
  pilot_areas: inputs/vectors/pilot_v2.geojson
  type:
    ref_data: ground_truth
    dets: ign

  
optimization_ign.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/optimization/ign
  tile_dir: inputs/tiles_ign
  ref_type: ground_truth
  ref_data:
    merged_reference: inputs/vectors/new_gt/ref_data.gpkg
    ground_truth: inputs/vectors/new_gt/ground_truth.gpkg
  aoi: inputs/vectors/pilot_v2.geojson
  dem_correspondence: inputs/tiles_ign/dem_per_aoi.csv
  non_sedimentary_areas: outputs/merged_DEM/ign/possible_areas/non_sedi_areas.gpkg


merge_dolines.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data/outputs/ign
  output_dir: .
  aoi: ../../inputs/vectors/pilot_v2.geojson
  dgm: DGM/sinkholes.gpkg
  evaporites: Evaporites/dolines.gpkg
  karst_nu: Karst nu/sinkholes.gpkg
  marnes_sur_karst: Marnes sur karst/sinkholes.gpkg
  molasse: Molasse/dolines.gpkg
  rsvmc: RSVMC/dolines.gpkg