download_tiles.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: inputs/tiles
  aoi: inputs/vectors/pilot_v3.gpkg
  buffer: 100
  method: level_set
  overwrite: False


merge_dem_over_aoi.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/merged_DEM/lidar_fct
  dem_dir: inputs/tiles
  dem_correspondence: inputs/tiles_ign/dem_per_aoi_level_set.csv
  aoi: inputs/vectors/pilot_v3.gpkg


level_set_depressions.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/lidar_lib
  dem_dir: outputs/merged_DEM/lidar_fct
  non_sedimentary_areas: inputs/vectors/non_sedimentary.parquet
  builtup_areas: inputs/vectors/restricted_siedlung_2024_2056.gpkg


post_processing.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/lidar_lib
  potential_dolines: outputs/lidar_lib/potential_dolines.gpkg
  tlm_data: inputs/vectors/side_data/clipped_tlm_subset.gpkg
  ground_cover_layer: tlm_bb_bodenbedeckung
  rivers: inputs/vectors/side_data/clipped_typisierung-fliessgewaesser_2056.gpkg


assess_results.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/assessment
  ref_data:
    merged_reference: inputs/vectors/new_gt/ref_data.gpkg
    ground_truth: inputs/vectors/new_gt/ground_truth.gpkg
  detections:
    level-set: outputs/lidar_lib/dolines.gpkg
    stochastic_depressions: outputs/stochastic_depressions/dep_2pt5_100/dolines.gpkg
  pilot_areas: inputs/vectors/pilot_v3.gpkg
  type:
    ref_data: ground_truth
    dets: level-set


optimization_level_set.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/optimization/level_set
  tile_dir: inputs/tiles
  ref_type: ground_truth
  ref_data:
    merged_reference: inputs/vectors/new_gt/ref_data.gpkg
    ground_truth: inputs/vectors/new_gt/ground_truth.gpkg
  study_param:
    new_study: True
    optimize: True
    iterations: 100
  aoi: inputs/vectors/pilot_v3.gpkg
  dem_correspondence: inputs/tiles/dem_per_aoi_level_set.csv
  non_sedimentary_areas: outputs/merged_DEM/ign/possible_areas/non_sedi_areas.gpkg
  builtup_areas: inputs/vectors/restricted_siedlung_2024_2056.gpkg
  tlm_data: inputs/vectors/side_data/clipped_tlm_subset.gpkg
  ground_cover_layer: tlm_bb_bodenbedeckung
  rivers: inputs/vectors/side_data/clipped_typisierung-fliessgewaesser_2056.gpkg