merge_gt.py:
    working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
    output_dir: inputs/vectors/new_gt
    aoi: inputs/vectors/pilot_v3.gpkg
    ref_data:
        geocover: inputs/vectors/dolines_hors_bati.gpkg
        tlm: inputs/vectors/TLM-Dolinen-20240814/tlm-dolinen_20240814.gpkg
        ne: inputs/vectors/NE/dolines_NE.geojson
    gt:
        chasseral: inputs/vectors/new_gt/chasseral_cleaned_up.shp
        point_gt: inputs/vectors/new_gt/new_dolines.gpkg
    points: True