download_tiles.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: inputs/tiles_watersheds
  aoi: inputs/vectors/pilot_v3.gpkg
  buffer: 2000
  overwrite: False


merge_dem_over_aoi.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/merged_DEM/wtsh
  dem_dir: inputs/tiles_watersheds
  dem_correspondence: inputs/tiles_watersheds/dem_per_aoi.csv
  aoi: inputs/vectors/pilot_v3.gpkg


depression_detection.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/dolines/wtshd
  dem_dir: outputs/merged_DEM/wtsh
  non_sedimentary_areas: inputs/vectors/non_sedimentary.parquet
  builtup_areas: inputs/vectors/restricted_siedlung_2024_2056.gpkg
  aoi: inputs/vectors/pilot_v3.gpkg


post_processing.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/dolines/wtshd
  potential_dolines: outputs/dolines/wtshd/potential_dolines.gpkg
  tlm_data: inputs/vectors/side_data/clipped_tlm_subset.gpkg
  ground_cover_layer: tlm_bb_bodenbedeckung
  rivers: inputs/vectors/side_data/clipped_typisierung-fliessgewaesser_2056.gpkg


assess_results.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/assessment
  dem_dir: outputs/merged_DEM/wtsh
  ref_data:
    merged_reference: inputs/vectors/new_gt/ref_data.gpkg
    ground_truth: inputs/vectors/new_gt/ground_truth.gpkg
  detections:
    watersheds: outputs/dolines/wtshd/dolines.gpkg
  pilot_areas: inputs/vectors/pilot_v3.gpkg
  type:
    ref_data: ground_truth
    dets: watersheds


optimization_watersheds.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/dolines/02_data
  output_dir: outputs/optimization/watersheds
  tile_dir: inputs/tiles_watersheds
  ref_type: ground_truth
  ref_data:
    merged_reference: inputs/vectors/new_gt/ref_data.gpkg
    ground_truth: inputs/vectors/new_gt/ground_truth.gpkg
  study_param:
    new_study: True
    optimize: True
    iterations: 100
  aoi: inputs/vectors/pilot_v3.gpkg
  dem_correspondence: inputs/tiles_watersheds/dem_per_aoi.csv
  non_sedimentary_areas: outputs/merged_DEM/ign/possible_areas/non_sedi_areas.gpkg
  builtup_areas: inputs/vectors/restricted_siedlung_2024_2056.gpkg
  tlm_data: inputs/vectors/side_data/clipped_tlm_subset.gpkg
  ground_cover_layer: tlm_bb_bodenbedeckung
  rivers: inputs/vectors/side_data/clipped_typisierung-fliessgewaesser_2056.gpkg