AOI_TYPE = 'Marnes sur karst'   # Possible types: None (i.e all types), DGM (Dépression sur glace morte), Evaporites, Karst nu, Marnes sur karst, Molasse, 
                            # RSVMC (Roches sédimentaires variées, à matrice calcaire)
ALL_PARAMS_IGN = {
    # Geocover
    'All types': {
        'resolution': 1.25,
        'max_slope': 3.5,
        'gaussian_kernel': 21,
        'gaussian_sigma': 7,
        'dem_diff_thrsld': 0.4,
        'min_area': 35,
        'limit_compactness': 0.2,
        'min_voronoi_area': 35000,
        'min_merged_area': 350000,
        'max_long_area': 3500,
        'min_long_compactness': 0.35,
        'min_round_compactness': 0.76,
        'thalweg_buffer': 3,
        'thalweg_threshold': 0.6,
        'max_depth': 90
    },
    'DGM': {
        'resolution': 3,
        'max_slope': 3.6,
        'gaussian_kernel': 27,
        'gaussian_sigma': 4.5,
        'dem_diff_thrsld': 3,
        'min_area': 25,
        'limit_compactness': 0.11,
        'min_voronoi_area': 95000,
        'min_merged_area': 350000,
        'max_long_area': 3500,
        'min_long_compactness': 0.5,
        'min_round_compactness': 0.69,
        'thalweg_buffer': 1.5,
        'thalweg_threshold': 0.7,
        'max_depth': 80
    },
    'Evaporites': {
        'resolution': 3,
        'max_slope': 1.8,
        'gaussian_kernel': 19,
        'gaussian_sigma': 6.5,
        'dem_diff_thrsld': 1.25,
        'min_area': 45,
        'limit_compactness': 0.225,
        'min_voronoi_area': 75000,
        'min_merged_area': 300000,
        'max_long_area': 2500,
        'min_long_compactness': 0.175,
        'min_round_compactness': 0.45,
        'thalweg_buffer': 6,
        'thalweg_threshold': 0.2,
        'max_depth': 70,
        'max_std_elev': 7
    },
    'Karst nu': {
        'resolution': 2.5,
        'max_slope': 4.8,
        'gaussian_kernel': 25,
        'gaussian_sigma': 7,
        'dem_diff_thrsld': 1.4,
        'min_area': 35,
        'limit_compactness': 0.325,
        'min_voronoi_area': 30000,
        'min_merged_area': 150000,
        'max_long_area': 1000,
        'min_long_compactness': 0.225,
        'min_round_compactness': 0.28,
        'thalweg_buffer': 5.5,
        'thalweg_threshold': 1.3,
        'max_depth': 135
    },
    'Marnes sur karst': {
        'resolution': 1,
        'max_slope': 2.6,
        'gaussian_kernel': 23,
        'gaussian_sigma': 6,
        'dem_diff_thrsld': 0.2,
        'min_area': 30,
        'limit_compactness': 0.375,
        'min_voronoi_area': 80000,
        'min_merged_area': 200000,
        'max_long_area': 4000,
        'min_long_compactness': 0.075,
        'min_round_compactness': 0.69,
        'thalweg_buffer': 2,
        'thalweg_threshold': 0.5,
        'max_depth': 65
    },
    'Molasse': {
        'resolution': 1.75,
        'max_slope': 3.6,
        'gaussian_kernel': 23,
        'gaussian_sigma': 7,
        'dem_diff_thrsld': 1.2,
        'min_area': 55,
        'limit_compactness': 0.3,
        'min_voronoi_area': 15000,
        'min_merged_area': 150000,
        'max_long_area': 3250,
        'min_long_compactness': 0.125,
        'min_round_compactness': 0.37,
        'thalweg_buffer': 2.5,
        'thalweg_threshold': 0.2,
        'max_depth': 125
    },
    'RSVMC': {
        'resolution': 2.75,
        'max_slope': 2.8,
        'gaussian_kernel': 23,
        'gaussian_sigma': 8,
        'dem_diff_thrsld': 1.8,
        'min_area': 35,
        'limit_compactness': 0.225,
        'min_voronoi_area': 60000,
        'min_merged_area': 50000,
        'max_long_area': 2750,
        'min_long_compactness': 0.1,
        'min_round_compactness': 0.34,
        'thalweg_buffer': 2.5,
        'thalweg_threshold': 0.9,
        'max_depth': 145
    },
    # TLM
    # 'All types': {
    #     'resolution': 3,
    #     'max_slope': 1.1,
    #     'gaussian_kernel': 31,
    #     'gaussian_sigma': 4.5,
    #     'dem_diff_thrsld': 1.5,
    #     'min_area': 100,
    #     'limit_compactness': 0.5,
    #     'min_voronoi_area': 30000,
    #     'min_merged_area': 200000,
    #     'max_long_area': 7000,
    #     'min_long_compactness': 0.3,
    #     'min_round_compactness': 0.1,
    #     'thalweg_buffer': 9,
    #     'thalweg_threshold': 0.3,
    #     'max_depth': 50
    # },
    # 'DGM': {
    #     'resolution': 1.75,
    #     'max_slope': 3,
    #     'gaussian_kernel': 31,
    #     'gaussian_sigma': 3.5,
    #     'dem_diff_thrsld': 3.5,
    #     'min_area': 35,
    #     'limit_compactness': 0.51,
    #     'min_voronoi_area': 80000,
    #     'min_merged_area': 250000,
    #     'max_long_area': 6000,
    #     'min_long_compactness': 0.4,
    #     'min_round_compactness': 0.57,
    #     'thalweg_buffer': 4.5,
    #     'thalweg_threshold': 0.8,
    #     'max_depth': 70
    # },
    # 'Evaporites': {
    #     'resolution': 5,
    #     'max_slope': 1.8,
    #     'gaussian_kernel': 21,
    #     'gaussian_sigma': 6,
    #     'dem_diff_thrsld': 0.8,
    #     'min_area': 80,
    #     'limit_compactness': 0.45,
    #     'min_voronoi_area': 10000,
    #     'min_merged_area': 125000,
    #     'max_long_area': 9000,
    #     'min_long_compactness': 0.15,
    #     'min_round_compactness': 0.57,
    #     'thalweg_buffer': 6,
    #     'thalweg_threshold': 0.5,
    #     'max_depth': 90
    # },
    # # 'Karst nu': {
    # #     'resolution': 30,
    # #     'max_slope': 1.5,
    # #     'gaussian_kernel': 25,
    # #     'gaussian_sigma': 3,
    # #     'dem_diff_thrsld': 0.5,
    # #     'min_area': 50,
    # #     'limit_compactness': 0.3,
    # #     'min_voronoi_area': 5000,
    # #     'min_merged_area': 100000,
    # #     'max_long_area': 2500,
    # #     'min_long_compactness': 0.1,
    # #     'min_round_compactness': 0.5,
    # #     'thalweg_buffer': 1,
    # #     'thalweg_threshold': 0.1,
    # #     'max_depth': 30
    # # },
    # 'Marnes sur karst': {
    #     'resolution': 2.75,
    #     'max_slope': 2.4,
    #     'gaussian_kernel': 19,
    #     'gaussian_sigma': 4.5,
    #     'dem_diff_thrsld': 1.3,
    #     'min_area': 35,
    #     'limit_compactness': 0.35,
    #     'min_voronoi_area': 45000,
    #     'min_merged_area': 300000,
    #     'max_long_area': 2000,
    #     'min_long_compactness': 0.2,
    #     'min_round_compactness': 0.72,
    #     'thalweg_buffer': 0.5,
    #     'thalweg_threshold': 1,
    #     'max_depth': 95
    # },
    # 'Molasse': {
    #     'resolution': 3.75,
    #     'max_slope': 3.8,
    #     'gaussian_kernel': 37,
    #     'gaussian_sigma': 3,
    #     'dem_diff_thrsld': 2.5,
    #     'min_area': 80,
    #     'limit_compactness': 0.2,
    #     'min_voronoi_area': 5000,
    #     'min_merged_area': 250000,
    #     'max_long_area': 4000,
    #     'min_long_compactness': 0.1,
    #     'min_round_compactness': 0.28,
    #     'thalweg_buffer': 0.5,
    #     'thalweg_threshold': 0.6,
    #     'max_depth': 140
    # },
    # 'RSVMC': {
    #     'resolution': 1.25,
    #     'max_slope': 2.2,
    #     'gaussian_kernel': 23,
    #     'gaussian_sigma': 6.5,
    #     'dem_diff_thrsld': 2.5,
    #     'min_area': 45,
    #     'limit_compactness': 0.3,
    #     'min_voronoi_area':40000,
    #     'min_merged_area': 200000,
    #     'max_long_area': 1500,
    #     'min_long_compactness': 0.2,
    #     'min_round_compactness': 0.32,
    #     'thalweg_buffer': 8,
    #     'thalweg_threshold': 0.7,
    #     'max_depth': 130
    # },
}
ALL_PARAMS_WATERSHEDS = {
    # Geocover
    'All types': {
        'resolution': 2,
        'simplification_param': 5,
        'mean_filter_size': 3,
        'fill_depth': 0.5,
        'max_part_in_lake': 0.1,
        'max_part_in_river': 0.1,
        'min_compactness': 0.5,
        'min_area': 35,
        'max_area': 2500,
        'min_diameter': 2,
        'min_depth': 0.1,
        'max_depth': 30
    },
    'DGM': {
        'resolution': 1.5,
        'simplification_param': 2.8,
        'mean_filter_size': 5,
        'fill_depth': 3.5,
        'max_part_in_lake': 0.25,
        'max_part_in_river': 0.15,
        'min_compactness': 0.4,
        'min_area': 20,
        'max_area': 3500,
        'min_diameter': 6,
        'min_depth': 0.5,
        'max_depth': 140
    },
    'Evaporites': {
        'resolution': 4,
        'simplification_param': 2.9,
        'mean_filter_size': 1,
        'fill_depth': 0.4,
        'max_part_in_lake': 0.25,
        'max_part_in_river': 0.1,
        'min_compactness': 0.55,
        'min_area': 65,
        'max_area': 4500,
        'min_diameter': 8.5,
        'min_depth': 0.3,
        'max_depth': 200,
        'max_std_elev': 7
    },
    'Karst nu': {
        'resolution': 2.5,
        'simplification_param': 1.7,
        'mean_filter_size': 1,
        'fill_depth': 1.9,
        'max_part_in_lake': 0.3,
        'max_part_in_river': 0.05,
        'min_compactness': 0.65,
        'min_area': 35,
        'max_area': 7500,
        'min_diameter': 9,
        'min_depth': 0.8,
        'max_depth': 105
    },
    'Marnes sur karst': {
        'resolution': 1,
        'simplification_param': 2.1,
        'mean_filter_size': 3,
        'fill_depth': 0.75,
        'max_part_in_lake': 0.05,
        'max_part_in_river': 0.35,
        'min_compactness': 0.25,
        'min_area': 15,
        'max_area': 6500,
        'min_diameter': 5.5,
        'min_depth': 0.9,
        'max_depth': 75
    },
    'Molasse': {
        'resolution': 1,
        'simplification_param': 3.6,
        'mean_filter_size': 3,
        'fill_depth': 0.75,
        'max_part_in_lake': 0.35,
        'max_part_in_river': 0.1,
        'min_compactness': 0.8,
        'min_area': 45,
        'max_area': 8000,
        'min_diameter': 4,
        'min_depth': 1.2,
        'max_depth': 75
    },
    'RSVMC': {
        'resolution': 1,
        'simplification_param': 0.3,
        'mean_filter_size': 1,
        'fill_depth': 2.25,
        'max_part_in_lake': 0.25,
        'max_part_in_river': 0.25,
        'min_compactness': 0.55,
        'min_area': 10,
        'max_area': 3500,
        'min_diameter': 9.5,
        'min_depth': 0.6,
        'max_depth': 110
    },
    # TLM
    # 'All types': {
    #     'resolution': 0.5,
    #     'simplification_param': 2.6,
    #     'mean_filter_size': 3,
    #     'fill_depth': 1.5,
    #     'max_part_in_lake': 0.15,
    #     'max_part_in_river': 0.2,
    #     'min_compactness': 0.9,
    #     'min_area': 10,
    #     'max_area': 9000,
    #     'min_diameter': 13.5,
    #     'min_depth': 0.9,
    #     'max_depth': 100
    # },
    # 'DGM': {
    #     'resolution': 4.75,
    #     'simplification_param': 3,
    #     'mean_filter_size': 1,
    #     'fill_depth': 5.75,
    #     'max_part_in_lake': 0.1,
    #     'max_part_in_river': 0.35,
    #     'min_compactness': 0.75,
    #     'min_area': 25,
    #     'max_area': 7000,
    #     'min_diameter': 7.5,
    #     'min_depth': 0.7,
    #     'max_depth': 125
    # },
    # 'Evaporites': {
    #     'resolution': 2,
    #     'simplification_param': 2.7,
    #     'mean_filter_size': 1,
    #     'fill_depth': 5.25,
    #     'max_part_in_lake': 0.5,
    #     'max_part_in_river': 0.2,
    #     'min_compactness': 0.8,
    #     'min_area': 30,
    #     'max_area': 7000,
    #     'min_diameter': 5,
    #     'min_depth': 0.4,
    #     'max_depth': 110
    # },
    # # 'Karst nu': {
    # #    'resolution': 2,
    # #     'simplification_param': 5,
    # #     'mean_filter_size': 3,
    # #     'fill_depth': 0.5,
    # #     'max_part_in_lake': 0.1,
    # #     'max_part_in_river': 0.1,
    # #     'min_compactness': 0.5,
    # #     'min_area': 35,
    # #     'max_area': 2500,
    # #     'min_diameter': 2,
    # #     'min_depth': 0.1,
    # #     'max_depth': 30
    # # },
    # 'Marnes sur karst': {
    #     'resolution': 1.25,
    #     'simplification_param': 2.4,
    #     'mean_filter_size': 1,
    #     'fill_depth': 3.5,
    #     'max_part_in_lake': 0.15,
    #     'max_part_in_river': 0.35,
    #     'min_compactness': 0.45,
    #     'min_area': 30,
    #     'max_area': 4000,
    #     'min_diameter': 12.5,
    #     'min_depth': 1.1,
    #     'max_depth': 180
    # },
    # 'Molasse': {
    #     'resolution': 2,
    #     'simplification_param': 1.2,
    #     'mean_filter_size': 1,
    #     'fill_depth': 4.25,
    #     'max_part_in_lake': 0.1,
    #     'max_part_in_river': 0.3,
    #     'min_compactness': 0.3,
    #     'min_area': 35,
    #     'max_area': 6500,
    #     'min_diameter': 3,
    #     'min_depth': 0.6,
    #     'max_depth': 150
    # },
    # 'RSVMC': {
    #     'resolution': 1.5,
    #     'simplification_param': 0.9,
    #     'mean_filter_size': 3,
    #     'fill_depth': 8.75,
    #     'max_part_in_lake': 0.1,
    #     'max_part_in_river': 0.3,
    #     'min_compactness': 0.3,
    #     'min_area': 20,
    #     'max_area': 7000,
    #     'min_diameter': 6.5,
    #     'min_depth': 0.6,
    #     'max_depth': 100
    # },
}